### ISSUE TITLE
kono-front - Refactoring: Desktop/Mobile NoticePanel & LostFoundPanel

### ISSUE THREAD

**Issue by inhibitor1217** [sparcs-kaist/kono#101]
구현할 Feature:

- [x] Smart/dumb component logic 분리
- [x] 모바일 디자인 적용
    - [x] 모바일에서는 pagination 없이 스크롤하면 뒤쪽 post를 더 불러오는 방식으로 작동
    - [x] Post image thumbnail 적용
        - [x] Default image
        - [x] Post image
    - 그런데 공지사항은 스크롤로 바꿔놓고 이미지는 왜 grid panel인가요 그냥 똑같이 만들면 더 예쁠텐데
- [x] Desktop에서 제목이 너무 길면 trim하는 logic 좀 더 잘 짜기 (module이 있을 것 같은데)
- ~Notice caching 구현~ 안해도됨

~그냥 앱을 새로 만드는 수준 ㅠㅠ~

**Comment by Sunnynah** [comment]
분실물은 한눈에 여러개가 보이는 게 더 좋을 것 같아서 grid로 했었는데 다시 생각해보니까 굳이 그럴 필요는 없을 것 같네요.bb 둘 다 스크롤로 할게요!

**Comment by inhibitor1217** [comment]
![Screenshot from 2019-11-14 15-31-41](https://user-images.githubusercontent.com/25701854/68832281-e2327a80-06f3-11ea-9ff3-08ad69b98fa8.png)
현재 사진처럼 `<img>` 태그에 붙은 `filter` property와 그 wrapper `<div>`에 붙은 `border-radius` property가 chrome에서 함께 작동하지 않는 문제점이 있습니다.
우리 코드의 문제점은 아니고 chrome의 문제점이라고 합니다.

> https://bugs.chromium.org/p/chromium/issues/detail?id=547937

**Comment by inhibitor1217** [comment]
![Screenshot from 2019-11-14 15-33-14](https://user-images.githubusercontent.com/25701854/68832373-1ad25400-06f4-11ea-85cb-6f75441a8b03.png)
사진처럼 firefox 에서는 정상 작동합니다.

**Comment by inhibitor1217** [comment]
하는 김에 caching까지 똑바로 구현해야 desktop <-> mobile 레이아웃 전환 시 똑바로 적용된다는 것을 알게 되었음 ^^
