### ISSUE TITLE
kono-front - Refactoring: Mobile NoticePanel & LostFoundPanel

### ISSUE THREAD

**Issue by Sunnynah** [sparcs-kaist/kono#108]
make overflow visible

**Comment by inhibitor1217** [comment]
CSS만 수정해서 해결할 수 있는 문제는 아니네요. (간단한 문제 아님)

다음 글 참조해서 scroll logic을 JS 단으로 옮겨야 할 듯
https://stackoverflow.com/questions/37392530/overflow-scroll-but-visible

**Comment by inhibitor1217** [comment]
는 꼼수를 써서 구현...
(그냥 component div를 전체 width를 차지하도록 하고 안쪽에 padding을 달았습니다.)

이렇게 하면 스크롤바가 안 예쁘게 나오는 문제점이 있으므로 마음에 안 들면 위 방법으로 하도록 하겠습니다ㅠ
![Screenshot from 2019-11-21 19-29-38](https://user-images.githubusercontent.com/25701854/69329967-67d69d00-0c95-11ea-923a-8e89b2c2d6ca.png)

**Comment by inhibitor1217** [comment]
branch: `kono-front-issue108`

**Comment by Sunnynah** [comment]
모바일에서는 스크롤바가 잘 안 보여서 이대로도 괜찮은 것 같아요
