### ISSUE TITLE
kono-front - Implementation: configuration menu 구현 및 브라우저에 설정 저장

### ISSUE THREAD

**Issue by inhibitor1217** [sparcs-kaist/kono#11]
~~1. Header에 언어, theme 등의 설정이 들어갈 수 있는 드롭다운 메뉴 컴포넌트를 작성한다.~~
- ~~`kono-front/src/components/DropdownMenu.js`, `kono-front/src/styles/DropdownMenu.module.scss`에 작성~~
- ~~메뉴 내에 들어갈 컴포넌트들은 `prop`으로 받을 수 있도록 설정~~
- ~~theme 고려할 것~~
- ~~hover나 클릭 시 펼쳐지는 메뉴~~

2. 설정을 브라우저에 저장하고, 앱 최초 렌더링 시 불러오도록 설정
- redux와 잘 연계해볼 것...
- 참고로 브라우저 메모리는 `window.localStorage`를 통해 접근할 수 있고 크롬 개발자 메뉴 - Application - Local Storage를 통해 디버깅 할 수 있다.
- 브라우저 메모리가 존재하지 않는 경우(?)를 대비한 error handling 할 것

**Comment by tink-expo** [comment]
Requested review at [https://github.com/sparcs-kaist/kono/pull/12](https://github.com/sparcs-kaist/kono/pull/12).
