### ISSUE TITLE
kono-front - Bug: Space btw components in iPad Mini

### ISSUE THREAD

**Issue by Sunnynah** [sparcs-kaist/kono#112]
![스크린샷 2019-11-21 오후 1 05 58](https://user-images.githubusercontent.com/32695733/69303277-ac474600-0c5f-11ea-969a-8c6159644196.png)
![스크린샷 2019-11-21 오후 1 04 48](https://user-images.githubusercontent.com/32695733/69303232-81f58880-0c5f-11ea-81f7-3cef9e7643b7.png)
아이패드 미니같이 윈도우 사이즈가 애매하게 작을 땐 room 컴포넌트 - 공지사항/분실물 컴포넌트 - footer 사이의 여백이 부족해 보입니다. 여백에 하한선을 정해야 할 것 같아요.

**Comment by inhibitor1217** [comment]
`kono-front-issue112` branch를 보시면 `LandingPage.module.scss`의 `.LandingPage__container` 클래스에 `padding-bottom` attribute를 추가하여 여백을 추가했습니다.

확인해보시고 직접 조절하셔도 됩니다 bb

`RoomPanel` - `NoticePanel/LostFoundPanel` 사이
![Screenshot from 2019-11-21 18-51-55](https://user-images.githubusercontent.com/25701854/69326928-08c25980-0c90-11ea-9ff4-7dfae4327dd6.png)

`NoticePanel/LostFoundPanel` - `LandingPage` 경계 사이
![Screenshot from 2019-11-21 18-52-02](https://user-images.githubusercontent.com/25701854/69326929-08c25980-0c90-11ea-8be7-0e862cc02332.png)

**Comment by inhibitor1217** [comment]
수정 사항 없으면 PR로 올려주세요
