### ISSUE TITLE
kono-front - Bug: 에러 핸들링 패널 위치

### ISSUE THREAD

**Issue by Sunnynah** [sparcs-kaist/kono#60]
주소창을 숨기면 에러 핸들링 패널의 위치가 달라져서 방 이미지에 가려집니다.
class = 'ErrorHandlingPanel'
<img width="891" alt="스크린샷 2019-10-20 오후 2 03 37" src="https://user-images.githubusercontent.com/32695733/67155060-6d616000-f342-11e9-81f6-f0f2228802dd.png">

**Comment by Sunnynah** [comment]
#57 Pull Request

**Comment by inhibitor1217** [comment]
이거랑 #8 이랑 모바일 페이지 구현이랑 묶어서 한번에 처리하면 될 것 같아요

**Comment by Sunnynah** [comment]
(모바일) 스크롤다운하면 주소창이 사라지고 스크롤업하면 주소창이 생기는 기능 때문에 RoomLegendPanel의 위치가 계속 바뀝니다. 주소창을 제외한 화면에서의 위치를 계산해야 할 것 같습니다.

**Comment by inhibitor1217** [comment]
#102 로 해결
