### ISSUE TITLE
kobo-front Bug: Room Panel onmouseover doesn't work

### ISSUE THREAD

**Issue by jwoo0122** [sparcs-kaist/kono#63]
No response for onMouseOver handler. Path doesn't catch mouse hover event.

**Comment by inhibitor1217** [comment]
지금 DB에 데이터가 하나도 없어서 `rooms` prop에 `[]`이 들어오는 상태입니다.
"데이터 없음" 상태인 방에 hover했을 때 panel이 올라오지 않는 것은 의도한 feature에요.

그런데 event 자체가 catch되지 않는 건 문제가 있어 보이네요 bb
