### ISSUE TITLE
kono-front - Bug: Responsive SVG size

### ISSUE THREAD

**Issue by inhibitor1217** [sparcs-kaist/kono#70]
window 크기에 따라 `RoomStatePanel`의 svg 크기가 달라지도록 구현하자.

**Comment by Sunnynah** [comment]
threshold1 까지는 양 옆의 여백 줄이기
threshold1 부터 svg 크기 줄이기
threshold2 부터 모바일 UI (각 room을 간단한 네모 블록으로 표현)

**Comment by inhibitor1217** [comment]
현재 데스크톱 레이아웃에서 절대적 크기 (600, 600)으로 RoomPanel 크기를 고정했습니다.
이렇게 해도 보기엔 괜찮긴 한데 혹시 일정한 비율을 유지하고 싶다면 이 이슈 유지하고, 아니면 닫도록 할게요
@Sunnynah

**Comment by Sunnynah** [comment]
> 현재 데스크톱 레이아웃에서 절대적 크기 (600, 600)으로 RoomPanel 크기를 고정했습니다.
> 이렇게 해도 보기엔 괜찮긴 한데 혹시 일정한 비율을 유지하고 싶다면 이 이슈 유지하고, 아니면 닫도록 할게요
> @Sunnynah

이대로도 괜찮은 것 같아요!
