### ISSUE TITLE
kono-api - Implementation: 이미지 업로드 API 추가

### ISSUE THREAD

**Issue by inhibitor1217** [sparcs-kaist/kono#78]
구현할 API: `POST /api/v1/image/upload`

- 구현 방법
    - HTTP POST method로 이미지를 받아 서버의 file system에 저장한다.
    - 이미지를 저장할 디렉토리는 환경 변수로 지정한다. (`.env` 파일 내용을 배포 환경마다 수정할 수 있도록)
    - 저장 시 이미지 파일명은 random hash string으로 지정한다. (uniqueness 보장되도록)
    - Response로 저장된 이미지의 path url을 가져온다.
- 옵션: 여러 장의 이미지를 한 번의 API 호출로 업로드하는 것도 가능한지?

- 실제로 `image` 테이블을 업데이트하는 것은 post를 작성하는 과정에서 진행되므로, 이 API에서는 생각하지 않아도 됨.

**Comment by inhibitor1217** [comment]
1. Slack DM으로 해결
2. Partial request가 뭐에요...? ㅠㅜ

**Comment by tink-expo** [comment]
큰 이미지를 전송할 때 한번에 던지면 여러가지 이슈가 발생할 수 있으니까 max chunk 를 지정해서 던지는건데 지금은 그냥 파일 크기 /개수를 쪼잔하게 줬습니다 ㅋㅋㅋ

**Comment by tink-expo** [comment]
Created pull request at https://github.com/sparcs-kaist/kono/pull/83.
